name: CI/CD Workflow for EC2 Deployment

on:
  push:
    branches:
      - main

jobs:
  ci:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant Execute Permission for Gradlew
      run: chmod +x gradlew

    - name: Create Configurations
      run: |
        mkdir -p src/main/resources
        echo "${{ secrets.APPLICATION_YML }}" > src/main/resources/application.yml
        echo "${{ secrets.KEYSTORE }}" | base64 --decode > src/main/resources/keystore.p12

    - name: Build Project
      run: ./gradlew clean build -x test

  cd:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: ci

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Docker Login
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build and Push Docker Image
      run: |
        docker build -t com-us-server .
        docker tag com-us-server hysong4u/com-us-server:latest
        docker push hysong4u/com-us-server:latest

    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        SERVER_ADDRESS: ${{ secrets.EC2_SERVER_ADDRESS }}
      run: |
        echo "$PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        ssh -T -o StrictHostKeyChecking=no -i private_key.pem ubuntu@$SERVER_ADDRESS << 'EOF'
          docker pull hysong4u/com-us-server:latest
          existing_container_id=$(sudo docker ps -q --filter "publish=443")
          if [ -n "$existing_container_id" ]; then
            sudo docker stop $existing_container_id
            sudo docker rm $existing_container_id
          fi
          sudo docker image prune -f
          docker run -d -p 443:443 hysong4u/com-us-server:latest
        EOF

        # docker 권한 문제 발생시
        # sudo chmod 660 /var/run/docker.sock
        # sudo /usr/sbin/usermod -aG docker $USER
        # sudo /usr/sbin/usermod -aG docker ubuntu
