name: dev CI/CD

on:
  push:
    branches: [ main ]

jobs:
  dev-ci-cd:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Latest Repo
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      # gradlew 파일에 실행 권한 부여

    - name: Create application.yml from secret
      run: |
        mkdir -p src/main/resources
        echo "${{ secrets.APPLICATION_YML }}" > src/main/resources/application.yml
      # GitHub Secrets에서 가져온 내용을 application.yml 파일로 생성

    - name: Build with Gradle
      run: ./gradlew clean build -x test

    - name: Docker build
      run: |
        echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        docker build -t COM-US-SERVER .
        docker tag COM-US-SERVER hysong4u/COM-US-SERVER:latest
        docker push hysong4u/COM-US-SERVER:latest

    - name: Get timestamp
      uses: gerred/actions/current-time@master
      id: current-time

    - name: Run string replace
      uses: frabert/replace-string-action@master
      id: format-time
      with:
        pattern: '[:\.]+'
        string: "${{ steps.current-time.outputs.time }}"
        replace-with: '-'
        flags: 'g'
