name: dev CI/CD

on:
  push:
    branches: [ main ]

jobs:
  dev-ci-cd:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Latest Repo
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      # gradlew 파일에 실행 권한 부여

    - name: Build with Gradle
      run: ./gradlew clean build -x test

    - name: Docker build
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
        docker build -t COM-US-SERVER .
        docker tag COM-US-SERVER hysong4u/COM-US-SERVER:latest
        docker push hysong4u/COM-US-SERVER:latest

    - name: Get timestamp
      uses: gerred/actions/current-time@master
      id: current-time
      # 현재 시간을 가져와 타임스탬프 생성

    - name: Run string replace
      uses: frabert/replace-string-action@master
      id: format-time
      with:
        pattern: '[:\.]+'
        string: "${{ steps.current-time.outputs.time }}"
        replace-with: '-'
        flags: 'g'
